DROP DATABASE IF EXISTS theater;
CREATE DATABASE theater; 
USE theater;

DROP TABLE IF EXISTS users;
CREATE TABLE users(
userName	VARCHAR(20) NOT NULL,
email		VARCHAR(20),
passw	VARCHAR(20),
PRIMARY KEY (userName)
);